services:
  - type: web
    name: skillnscale-api
    runtime: docker
    repo: https://github.com/skillnscaleindia/SkillnScale-Backend
    branch: main
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dwcm6rqyx
      - key: CLOUDINARY_API_KEY
        value: 998782166913584
      - key: CLOUDINARY_API_SECRET
        value: vg3JZF0_69vtRLpRvPKxs0vY5t8
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
